name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main
env:
  MAIN_PYTHON_VERSION : '3.10'
  PACKAGE_NAME: 'ansys-sphinx-theme'
  PACKAGE_NAMESPACE: 'ansys_sphinx_theme'
  DOCUMENTATION_CNAME: 'sphinxdocs.ansys.com'
  MEILISEARCH_API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
  MEILISEARCH_PUBLIC_API_KEY: ${{ secrets.MEILISEARCH_PUBLIC_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  windows-doc-build:
    name: "Windows Doc build"
    runs-on: windows-latest
    needs: doc-style
    steps:
      - name: "Build documentation"
        uses: SMoraisAnsys/actions/_windows_doc-build@refact/doc-build
        with:
          skip-install: true
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: false
